<a href="https://colab.research.google.com/github/anchalsinha-0411/Data-Cleaning-In-Machine-Learning/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Untitled folder/olympics.csv')

Data Cleaning is used to remove the impurity of data or unused data

In [ ]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,? Summer,01 !,02 !,03 !,Total,? Winter,01 !,02 !,03 !,Total,? Games,01 !,02 !,03 !,Combined total
1,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
2,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12

In [ ]:
df.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
143,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
144,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
145,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
146,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
147,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [ ]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
count,147,148,148,148,148,148,148,148,148,148,148,148,148,148,148,148
unique,147,28,55,55,57,76,22,26,25,28,35,45,56,55,64,75
top,Afghanistan (AFG),5,0,1,0,1,0,0,0,0,0,11,0,1,0,1
freq,1,17,47,27,23,26,45,109,104,105,101,17,46,26,22,26

In [ ]:
df.shape

(148, 16)

In [ ]:
df.dtypes

0     object
1     object
2     object
3     object
4     object
5     object
6     object
7     object
8     object
9     object
10    object
11    object
12    object
13    object
14    object
15    object
dtype: object

In [ ]:
df.isnull()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
144,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
145,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
146,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
147,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
# Assuming you want to use the first column as the index and skip the first row.
# Adjust the values if needed based on your data
df = pd.read_csv('/content/drive/MyDrive/Untitled folder/olympics.csv', index_col=0, skiprows=[0])
display(df.head())

,? Summer,01 !,02 !,03 !,Total,? Winter,01 !.1,02 !.1,03 !.1,Total.1,? Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [ ]:
df.columns

Index(['? Summer', '01 !', '02 !', '03 !', 'Total', '? Winter', '01 !.1',
       '02 !.1', '03 !.1', 'Total.1', '? Games', '01 !.2', '02 !.2', '03 !.2',
       'Combined total'],
      dtype='object')

In [ ]:
for col in df.columns:
  if col[:2]=='01':
    df.rename(columns={col:'Gold'+col[4:]},inplace=True)
  if col[:2]=='02':
    df.rename(columns={col:'Silver'+col[4:]},inplace=True)
  if col[:2]=='03':
    df.rename(columns={col:'Bronze'+col[4:]},inplace=True)
  if col[:1]=='?':
    df.rename(columns={col:'#'+col[1:]},inplace=True)


df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [ ]:
df['Gold']>0 #boolean masking

Afghanistan (AFG)                               False
Algeria (ALG)                                    True
Argentina (ARG)                                  True
Armenia (ARM)                                    True
Australasia (ANZ) [ANZ]                          True
                                                ...
Independent Olympic Participants (IOP) [IOP]    False
Zambia (ZAM) [ZAM]                              False
Zimbabwe (ZIM) [ZIM]                             True
Mixed team (ZZX) [ZZX]                           True
Totals                                           True
Name: Gold, Length: 147, dtype: bool

In [ ]:
only_gold=df.where(df['Gold']>0)
only_gold.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Afghanistan (AFG),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Algeria (ALG),12.0,5.0,2.0,8.0,15.0,3.0,0.0,0.0,0.0,0.0,15.0,5.0,2.0,8.0,15.0
Argentina (ARG),23.0,18.0,24.0,28.0,70.0,18.0,0.0,0.0,0.0,0.0,41.0,18.0,24.0,28.0,70.0
Armenia (ARM),5.0,1.0,2.0,9.0,12.0,6.0,0.0,0.0,0.0,0.0,11.0,1.0,2.0,9.0,12.0
Australasia (ANZ) [ANZ],2.0,3.0,4.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,5.0,12.0

In [ ]:
only_gold['Gold'].count() #counting data cell

np.int64(100)

In [ ]:
df['Gold'].count()

np.int64(147)

In [ ]:
only_gold.isnull().sum()

# Summer          47
Gold              47
Silver            47
Bronze            47
Total             47
# Winter          47
Gold.1            47
Silver.1          47
Bronze.1          47
Total.1           47
# Games           47
Gold.2            47
Silver.2          47
Bronze.2          47
Combined total    47
dtype: int64

In [ ]:
only_gold=only_gold.dropna() #to drop a specific column
only_gold.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Algeria (ALG),12.0,5.0,2.0,8.0,15.0,3.0,0.0,0.0,0.0,0.0,15.0,5.0,2.0,8.0,15.0
Argentina (ARG),23.0,18.0,24.0,28.0,70.0,18.0,0.0,0.0,0.0,0.0,41.0,18.0,24.0,28.0,70.0
Armenia (ARM),5.0,1.0,2.0,9.0,12.0,6.0,0.0,0.0,0.0,0.0,11.0,1.0,2.0,9.0,12.0
Australasia (ANZ) [ANZ],2.0,3.0,4.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,5.0,12.0
Australia (AUS) [AUS] [Z],25.0,139.0,152.0,177.0,468.0,18.0,5.0,3.0,4.0,12.0,43.0,144.0,155.0,181.0,480.0

In [ ]:
only_gold.isnull().sum()

# Summer          0
Gold              0
Silver            0
Bronze            0
Total             0
# Winter          0
Gold.1            0
Silver.1          0
Bronze.1          0
Total.1           0
# Games           0
Gold.2            0
Silver.2          0
Bronze.2          0
Combined total    0
dtype: int64

In [ ]:
df=df.reset_index()
df=df.set_index(['Gold'])
df.head()

,index,# Summer,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Gold,,,,,,,,,,,,,,,
0,Afghanistan (AFG),13,0,2,2,0,0,0,0,0,13,0,0,2,2
5,Algeria (ALG),12,2,8,15,3,0,0,0,0,15,5,2,8,15
18,Argentina (ARG),23,24,28,70,18,0,0,0,0,41,18,24,28,70
1,Armenia (ARM),5,2,9,12,6,0,0,0,0,11,1,2,9,12
3,Australasia (ANZ) [ANZ],2,4,5,12,0,0,0,0,0,2,3,4,5,12

In [ ]:
only_gold['Gold'].count()

np.int64(100)

In [ ]:
df=df.reset_index()
df.head()

,Gold,index,# Summer,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
0,0,Afghanistan (AFG),13,0,2,2,0,0,0,0,0,13,0,0,2,2
1,5,Algeria (ALG),12,2,8,15,3,0,0,0,0,15,5,2,8,15
2,18,Argentina (ARG),23,24,28,70,18,0,0,0,0,41,18,24,28,70
3,1,Armenia (ARM),5,2,9,12,6,0,0,0,0,11,1,2,9,12
4,3,Australasia (ANZ) [ANZ],2,4,5,12,0,0,0,0,0,2,3,4,5,12

In [ ]:
df=df.set_index(['Gold','Gold.1'])
df.head()

,,index,# Summer,Silver,Bronze,Total,# Winter,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Gold,Gold.1,,,,,,,,,,,,,,
0,0,Afghanistan (AFG),13,0,2,2,0,0,0,0,13,0,0,2,2
5,0,Algeria (ALG),12,2,8,15,3,0,0,0,15,5,2,8,15
18,0,Argentina (ARG),23,24,28,70,18,0,0,0,41,18,24,28,70
1,0,Armenia (ARM),5,2,9,12,6,0,0,0,11,1,2,9,12
3,0,Australasia (ANZ) [ANZ],2,4,5,12,0,0,0,0,2,3,4,5,12

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/Untitled folder/log.csv')

In [ ]:
df1

          time    user          video  playback position paused  volume
0   1469974424  cheryl     intro.html                  5  False    10.0
1   1469974454  cheryl     intro.html                  6    NaN     NaN
2   1469974544  cheryl     intro.html                  9    NaN     NaN
3   1469974574  cheryl     intro.html                 10    NaN     NaN
4   1469977514     bob     intro.html                  1    NaN     NaN
5   1469977544     bob     intro.html                  1    NaN     NaN
6   1469977574     bob     intro.html                  1    NaN     NaN
7   1469977604     bob     intro.html                  1    NaN     NaN
8   1469974604  cheryl     intro.html                 11    NaN     NaN
9   1469974694  cheryl     intro.html                 14    NaN     NaN
10  1469974724  cheryl     intro.html                 15    NaN     NaN
11  1469974454     sue  advanced.html                 24    NaN     NaN
12  1469974524     sue  advanced.html                 25    NaN     NaN
13  1469974424     sue  advanced.html                 23  False    10.0
14  1469974554     sue  advanced.html                 26    NaN     NaN
15  1469974624     sue  advanced.html                 27    NaN     NaN
16  1469974654     sue  advanced.html                 28    NaN     5.0
17  1469974724     sue  advanced.html                 29    NaN     NaN
18  1469974484  cheryl     intro.html                  7    NaN     NaN
19  1469974514  cheryl     intro.html                  8    NaN     NaN
20  1469974754     sue  advanced.html                 30    NaN     NaN
21  1469974824     sue  advanced.html                 31    NaN     NaN
22  1469974854     sue  advanced.html                 32    NaN     NaN
23  1469974924     sue  advanced.html                 33    NaN     NaN
24  1469977424     bob     intro.html                  1   True    10.0
25  1469977454     bob     intro.html                  1    NaN     NaN
26  1469977484     bob     intro.html                  1    NaN     NaN
27  1469977634     bob     intro.html                  1    NaN     NaN
28  1469977664     bob     intro.html                  1    NaN     NaN
29  1469974634  cheryl     intro.html                 12    NaN     NaN
30  1469974664  cheryl     intro.html                 13    NaN     NaN
31  1469977694     bob     intro.html                  1    NaN     NaN
32  1469977724     bob     intro.html                  1    NaN     NaN

In [ ]:
df1.head()

         time    user       video  playback position paused  volume
0  1469974424  cheryl  intro.html                  5  False    10.0
1  1469974454  cheryl  intro.html                  6    NaN     NaN
2  1469974544  cheryl  intro.html                  9    NaN     NaN
3  1469974574  cheryl  intro.html                 10    NaN     NaN
4  1469977514     bob  intro.html                  1    NaN     NaN

In [ ]:
df1.tail()

          time    user       video  playback position paused  volume
28  1469977664     bob  intro.html                  1    NaN     NaN
29  1469974634  cheryl  intro.html                 12    NaN     NaN
30  1469974664  cheryl  intro.html                 13    NaN     NaN
31  1469977694     bob  intro.html                  1    NaN     NaN
32  1469977724     bob  intro.html                  1    NaN     NaN

In [ ]:
df1.describe()

               time  playback position  volume
count  3.300000e+01          33.000000    4.00
mean   1.469976e+09          13.000000    8.75
std    1.420109e+03          11.696688    2.50
min    1.469974e+09           1.000000    5.00
25%    1.469975e+09           1.000000    8.75
50%    1.469975e+09          10.000000   10.00
75%    1.469977e+09          25.000000   10.00
max    1.469978e+09          33.000000   10.00

In [ ]:
df1.count()

time                 33
user                 33
video                33
playback position    33
paused                3
volume                4
dtype: int64

In [ ]:
df1.isnull()

     time   user  video  playback position  paused  volume
0   False  False  False              False   False   False
1   False  False  False              False    True    True
2   False  False  False              False    True    True
3   False  False  False              False    True    True
4   False  False  False              False    True    True
5   False  False  False              False    True    True
6   False  False  False              False    True    True
7   False  False  False              False    True    True
8   False  False  False              False    True    True
9   False  False  False              False    True    True
10  False  False  False              False    True    True
11  False  False  False              False    True    True
12  False  False  False              False    True    True
13  False  False  False              False   False   False
14  False  False  False              False    True    True
15  False  False  False              False    True    True
16  False  False  False              False    True   False
17  False  False  False              False    True    True
18  False  False  False              False    True    True
19  False  False  False              False    True    True
20  False  False  False              False    True    True
21  False  False  False              False    True    True
22  False  False  False              False    True    True
23  False  False  False              False    True    True
24  False  False  False              False   False   False
25  False  False  False              False    True    True
26  False  False  False              False    True    True
27  False  False  False              False    True    True
28  False  False  False              False    True    True
29  False  False  False              False    True    True
30  False  False  False              False    True    True
31  False  False  False              False    True    True
32  False  False  False              False    True    True

In [ ]:
df1.isnull().sum()

time                  0
user                  0
video                 0
playback position     0
paused               30
volume               29
dtype: int64

In [ ]:
df1.dtypes

time                   int64
user                  object
video                 object
playback position      int64
paused                object
volume               float64
dtype: object

In [ ]:
df1 = df1.set_index('time')
df1

              user          video  playback position paused  volume
time
1469974424  cheryl     intro.html                  5  False    10.0
1469974454  cheryl     intro.html                  6    NaN     NaN
1469974544  cheryl     intro.html                  9    NaN     NaN
1469974574  cheryl     intro.html                 10    NaN     NaN
1469977514     bob     intro.html                  1    NaN     NaN
1469977544     bob     intro.html                  1    NaN     NaN
1469977574     bob     intro.html                  1    NaN     NaN
1469977604     bob     intro.html                  1    NaN     NaN
1469974604  cheryl     intro.html                 11    NaN     NaN
1469974694  cheryl     intro.html                 14    NaN     NaN
1469974724  cheryl     intro.html                 15    NaN     NaN
1469974454     sue  advanced.html                 24    NaN     NaN
1469974524     sue  advanced.html                 25    NaN     NaN
1469974424     sue  advanced.html                 23  False    10.0
1469974554     sue  advanced.html                 26    NaN     NaN
1469974624     sue  advanced.html                 27    NaN     NaN
1469974654     sue  advanced.html                 28    NaN     5.0
1469974724     sue  advanced.html                 29    NaN     NaN
1469974484  cheryl     intro.html                  7    NaN     NaN
1469974514  cheryl     intro.html                  8    NaN     NaN
1469974754     sue  advanced.html                 30    NaN     NaN
1469974824     sue  advanced.html                 31    NaN     NaN
1469974854     sue  advanced.html                 32    NaN     NaN
1469974924     sue  advanced.html                 33    NaN     NaN
1469977424     bob     intro.html                  1   True    10.0
1469977454     bob     intro.html                  1    NaN     NaN
1469977484     bob     intro.html                  1    NaN     NaN
1469977634     bob     intro.html                  1    NaN     NaN
1469977664     bob     intro.html                  1    NaN     NaN
1469974634  cheryl     intro.html                 12    NaN     NaN
1469974664  cheryl     intro.html                 13    NaN     NaN
1469977694     bob     intro.html                  1    NaN     NaN
1469977724     bob     intro.html                  1    NaN     NaN

In [ ]:
df1=df1.sort_index()
df1

              user          video  playback position paused  volume
time
1469974424  cheryl     intro.html                  5  False    10.0
1469974424     sue  advanced.html                 23  False    10.0
1469974454     sue  advanced.html                 24    NaN     NaN
1469974454  cheryl     intro.html                  6    NaN     NaN
1469974484  cheryl     intro.html                  7    NaN     NaN
1469974514  cheryl     intro.html                  8    NaN     NaN
1469974524     sue  advanced.html                 25    NaN     NaN
1469974544  cheryl     intro.html                  9    NaN     NaN
1469974554     sue  advanced.html                 26    NaN     NaN
1469974574  cheryl     intro.html                 10    NaN     NaN
1469974604  cheryl     intro.html                 11    NaN     NaN
1469974624     sue  advanced.html                 27    NaN     NaN
1469974634  cheryl     intro.html                 12    NaN     NaN
1469974654     sue  advanced.html                 28    NaN     5.0
1469974664  cheryl     intro.html                 13    NaN     NaN
1469974694  cheryl     intro.html                 14    NaN     NaN
1469974724  cheryl     intro.html                 15    NaN     NaN
1469974724     sue  advanced.html                 29    NaN     NaN
1469974754     sue  advanced.html                 30    NaN     NaN
1469974824     sue  advanced.html                 31    NaN     NaN
1469974854     sue  advanced.html                 32    NaN     NaN
1469974924     sue  advanced.html                 33    NaN     NaN
1469977424     bob     intro.html                  1   True    10.0
1469977454     bob     intro.html                  1    NaN     NaN
1469977484     bob     intro.html                  1    NaN     NaN
1469977514     bob     intro.html                  1    NaN     NaN
1469977544     bob     intro.html                  1    NaN     NaN
1469977574     bob     intro.html                  1    NaN     NaN
1469977604     bob     intro.html                  1    NaN     NaN
1469977634     bob     intro.html                  1    NaN     NaN
1469977664     bob     intro.html                  1    NaN     NaN
1469977694     bob     intro.html                  1    NaN     NaN
1469977724     bob     intro.html                  1    NaN     NaN

In [ ]:
df1=df1.dropna()
df1

              user          video  playback position paused  volume
time
1469974424  cheryl     intro.html                  5  False    10.0
1469974424     sue  advanced.html                 23  False    10.0
1469977424     bob     intro.html                  1   True    10.0

In [ ]:
df1=df1.fillna(method='ffill')
df1.head()

/tmp/ipython-input-508570978.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1=df1.fillna(method='ffill')
/tmp/ipython-input-508570978.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1=df1.fillna(method='ffill')

              user          video  playback position  paused  volume
time
1469974424  cheryl     intro.html                  5   False    10.0
1469974424     sue  advanced.html                 23   False    10.0
1469977424     bob     intro.html                  1    True    10.0

In [ ]:
df1=df1.fillna(method='bfill')
df1.head()

/tmp/ipython-input-4114811944.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1=df1.fillna(method='bfill')

              user          video  playback position  paused  volume
time
1469974424  cheryl     intro.html                  5   False    10.0
1469974424     sue  advanced.html                 23   False    10.0
1469977424     bob     intro.html                  1    True    10.0

#FIFA DATA CLEANING WITH FILLNA

In [ ]:
df2=pd.read_csv('/content/drive/MyDrive/Untitled folder/fifa_cleaned.csv')

In [ ]:
df2

,id,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,1987-06-24,31,170.18,72.1,"CF,RW,ST",Argentina,94,...,64+2,61+2,61+2,61+2,64+2,59+2,48+2,48+2,48+2,59+2
1,190460,C. Eriksen,Christian Dannemann Eriksen,1992-02-14,27,154.94,76.2,"CAM,RM,CM",Denmark,88,...,71+3,71+3,71+3,71+3,71+3,66+3,57+3,57+3,57+3,66+3
2,195864,P. Pogba,Paul Pogba,1993-03-15,25,190.50,83.9,"CM,CAM",France,88,...,76+3,77+3,77+3,77+3,76+3,74+3,72+3,72+3,72+3,74+3
3,198219,L. Insigne,Lorenzo Insigne,1991-06-04,27,162.56,59.0,"LW,ST",Italy,88,...,63+3,58+3,58+3,58+3,63+3,58+3,44+3,44+3,44+3,58+3
4,201024,K. Koulibaly,Kalidou Koulibaly,1991-06-20,27,187.96,88.9,CB,Senegal,88,...,73+3,77+3,77+3,77+3,73+3,76+3,85+3,85+3,85+3,76+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,204322,R. McKenzie,Rory McKenzie,1993-10-07,25,175.26,74.8,"RM,CAM,CM",Scotland,67,...,53+2,52+2,52+2,52+2,53+2,50+2,46+2,46+2,46+2,50+2
17950,239762,M. Sipľak,Michal Sipľak,1996-02-02,23,182.88,79.8,LB,Slovakia,59,...,57+2,55+2,55+2,55+2,57+2,57+2,58+2,58+2,58+2,57+2
17951,235155,J. Bekkema,Jan Bekkema,1996-04-09,22,185.42,89.8,GK,Netherlands,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17952,244883,A. Al Yami,Abdulrahman Al Yami,1997-06-19,21,175.26,64.9,"ST,LM",Saudi Arabia,59,...,41+2,35+2,35+2,35+2,41+2,39+2,32+2,32+2,32+2,39+2
17953,247187,Júnior Brumado,José Francisco dos Santos Júnior,1999-05-15,19,190.50,79.8,ST,Brazil,59,...,41+2,40+2,40+2,40+2,41+2,40+2,40+2,40+2,40+2,40+2

In [ ]:
df2.head()

,id,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,1987-06-24,31,170.18,72.1,"CF,RW,ST",Argentina,94,...,64+2,61+2,61+2,61+2,64+2,59+2,48+2,48+2,48+2,59+2
1,190460,C. Eriksen,Christian Dannemann Eriksen,1992-02-14,27,154.94,76.2,"CAM,RM,CM",Denmark,88,...,71+3,71+3,71+3,71+3,71+3,66+3,57+3,57+3,57+3,66+3
2,195864,P. Pogba,Paul Pogba,1993-03-15,25,190.50,83.9,"CM,CAM",France,88,...,76+3,77+3,77+3,77+3,76+3,74+3,72+3,72+3,72+3,74+3
3,198219,L. Insigne,Lorenzo Insigne,1991-06-04,27,162.56,59.0,"LW,ST",Italy,88,...,63+3,58+3,58+3,58+3,63+3,58+3,44+3,44+3,44+3,58+3
4,201024,K. Koulibaly,Kalidou Koulibaly,1991-06-20,27,187.96,88.9,CB,Senegal,88,...,73+3,77+3,77+3,77+3,73+3,76+3,85+3,85+3,85+3,76+3

In [ ]:
df2.tail()

,id,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
17949,204322,R. McKenzie,Rory McKenzie,1993-10-07,25,175.26,74.8,"RM,CAM,CM",Scotland,67,...,53+2,52+2,52+2,52+2,53+2,50+2,46+2,46+2,46+2,50+2
17950,239762,M. Sipľak,Michal Sipľak,1996-02-02,23,182.88,79.8,LB,Slovakia,59,...,57+2,55+2,55+2,55+2,57+2,57+2,58+2,58+2,58+2,57+2
17951,235155,J. Bekkema,Jan Bekkema,1996-04-09,22,185.42,89.8,GK,Netherlands,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17952,244883,A. Al Yami,Abdulrahman Al Yami,1997-06-19,21,175.26,64.9,"ST,LM",Saudi Arabia,59,...,41+2,35+2,35+2,35+2,41+2,39+2,32+2,32+2,32+2,39+2
17953,247187,Júnior Brumado,José Francisco dos Santos Júnior,1999-05-15,19,190.50,79.8,ST,Brazil,59,...,41+2,40+2,40+2,40+2,41+2,40+2,40+2,40+2,40+2,40+2

In [ ]:
df2.describe()

,id,age,height_cm,weight_kgs,overall_rating,potential,value_euro,wage_euro,international_reputation(1-5),weak_foot(1-5),...,penalties,composure,marking,standing_tackle,sliding_tackle,GK_diving,GK_handling,GK_kicking,GK_positioning,GK_reflexes
count,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,1.769900e+04,17708.000000,17954.000000,17954.000000,...,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000
mean,215411.087780,25.565445,174.946921,75.301047,66.240169,71.430935,2.479280e+06,9902.134628,1.111674,2.945695,...,48.357302,58.680183,47.162861,47.733040,45.705915,16.784449,16.556199,16.388660,16.541049,16.874067
std,29758.387106,4.705708,14.029449,7.083684,6.963730,6.131339,5.687014e+06,21995.593750,0.392168,0.663691,...,15.810844,11.625541,20.037346,21.674973,21.285812,17.893895,17.108234,16.701447,17.231495,18.182943
min,16.000000,17.000000,152.400000,49.900000,47.000000,48.000000,1.000000e+04,1000.000000,1.000000,1.000000,...,5.000000,12.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,201117.250000,22.000000,154.940000,69.900000,62.000000,67.000000,3.250000e+05,1000.000000,1.000000,3.000000,...,38.000000,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,222919.000000,25.000000,175.260000,74.800000,66.000000,71.000000,7.000000e+05,3000.000000,1.000000,3.000000,...,49.000000,60.000000,52.500000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,237613.500000,29.000000,185.420000,79.800000,71.000000,75.000000,2.100000e+06,9000.000000,1.000000,3.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,247607.000000,46.000000,205.740000,110.200000,94.000000,95.000000,1.105000e+08,565000.000000,5.000000,5.000000,...,92.000000,96.000000,94.000000,93.000000,90.000000,90.000000,92.000000,92.000000,90.000000,94.000000

In [ ]:
df2.dtypes

id             int64
name          object
full_name     object
birth_date    object
age            int64
               ...
LB            object
LCB           object
CB            object
RCB           object
RB            object
Length: 92, dtype: object

In [ ]:
df2.count()

id            17954
name          17954
full_name     17954
birth_date    17954
age           17954
              ...
LB            15889
LCB           15889
CB            15889
RCB           15889
RB            15889
Length: 92, dtype: int64

In [ ]:
df2.isnull()

,id,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17950,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17951,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
17952,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17953,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df2.isnull().sum()

id               0
name             0
full_name        0
birth_date       0
age              0
              ...
LB            2065
LCB           2065
CB            2065
RCB           2065
RB            2065
Length: 92, dtype: int64

In [ ]:
df2=df2.set_index('id')
df2.head()

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
id,,,,,,,,,,,,,,,,,,,,,
158023,L. Messi,Lionel Andrés Messi Cuccittini,1987-06-24,31,170.18,72.1,"CF,RW,ST",Argentina,94,94,...,64+2,61+2,61+2,61+2,64+2,59+2,48+2,48+2,48+2,59+2
190460,C. Eriksen,Christian Dannemann Eriksen,1992-02-14,27,154.94,76.2,"CAM,RM,CM",Denmark,88,89,...,71+3,71+3,71+3,71+3,71+3,66+3,57+3,57+3,57+3,66+3
195864,P. Pogba,Paul Pogba,1993-03-15,25,190.50,83.9,"CM,CAM",France,88,91,...,76+3,77+3,77+3,77+3,76+3,74+3,72+3,72+3,72+3,74+3
198219,L. Insigne,Lorenzo Insigne,1991-06-04,27,162.56,59.0,"LW,ST",Italy,88,88,...,63+3,58+3,58+3,58+3,63+3,58+3,44+3,44+3,44+3,58+3
201024,K. Koulibaly,Kalidou Koulibaly,1991-06-20,27,187.96,88.9,CB,Senegal,88,91,...,73+3,77+3,77+3,77+3,73+3,76+3,85+3,85+3,85+3,76+3

In [ ]:
df2=df2.sort_index()
df2.head()

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
id,,,,,,,,,,,,,,,,,,,,,
16,Luis García,Luis García Fernández,1981-02-06,38,152.40,64.9,"CM,CAM,CDM",Spain,71,71,...,62+2,65+2,65+2,65+2,62+2,59+2,59+2,59+2,59+2,59+2
41,Iniesta,Andrés Iniesta Luján,1984-05-11,34,170.18,68.0,"CM,LM",Spain,85,85,...,71+3,73+3,73+3,73+3,71+3,68+3,63+3,63+3,63+3,68+3
80,E. Belözoğlu,Emre Belözoğlu,1980-09-07,38,170.18,72.1,"CM,CDM",Turkey,79,79,...,68+2,73+2,73+2,73+2,68+2,65+2,65+2,65+2,65+2,65+2
657,D. Vaughan,David Vaughan,1983-02-18,36,167.64,69.9,"CM,CDM",Wales,64,64,...,58+2,62+2,62+2,62+2,58+2,58+2,61+2,61+2,61+2,58+2
768,Felipe,Felipe Dias da Silva dal Belo,1984-07-31,34,187.96,74.8,CB,Brazil,75,75,...,61+2,68+2,68+2,68+2,61+2,64+2,73+2,73+2,73+2,64+2

In [ ]:
df2=df2.dropna()
df2

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
id,,,,,,,,,,,,,,,,,,,,,
20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,1985-02-05,34,187.96,83.0,"ST,LW",Portugal,94,94,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
138956,G. Chiellini,Giorgio Chiellini,1984-08-14,34,187.96,84.8,CB,Italy,90,90,...,74+3,76+3,76+3,76+3,74+3,77+3,86+3,86+3,86+3,77+3
139720,V. Kompany,Vincent Kompany,1986-04-10,32,190.50,84.8,CB,Belgium,85,85,...,73+3,77+3,77+3,77+3,73+3,75+3,82+3,82+3,82+3,75+3
153079,S. Agüero,Sergio Leonel Agüero del Castillo,1988-06-02,30,172.72,69.9,ST,Argentina,89,89,...,58+3,56+3,56+3,56+3,58+3,53+3,47+3,47+3,47+3,53+3
155862,Sergio Ramos,Sergio Ramos García,1986-03-30,32,182.88,82.1,CB,Spain,90,90,...,81+3,84+3,84+3,84+3,81+3,83+3,87+3,87+3,87+3,83+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234396,A. Davies,Alphonso Davies,2000-11-02,18,154.94,72.1,"LM,RM",Canada,72,87,...,65+2,61+2,61+2,61+2,65+2,64+2,60+2,60+2,60+2,64+2
235243,M. de Ligt,Matthijs de Ligt,1999-08-12,19,187.96,88.9,CB,Netherlands,83,92,...,74+2,77+2,77+2,77+2,74+2,75+2,81+2,81+2,81+2,75+2
235320,B. Johnsen,Björn Maars Johnsen,1991-11-06,27,195.58,81.2,ST,Norway,72,73,...,51+2,50+2,50+2,50+2,51+2,50+2,50+2,50+2,50+2,50+2
235569,T. Ndombele,Tanguy NDombèlé Alvaro,1996-12-28,22,154.94,76.2,"CM,CDM",France,80,89,...,75+2,76+2,76+2,76+2,75+2,73+2,72+2,72+2,72+2,73+2
238555,J. Savarino,Jefferson Savarino,1996-11-11,22,170.18,66.2,"RW,CAM",Venezuela,72,82,...,57+2,54+2,54+2,54+2,57+2,54+2,46+2,46+2,46+2,54+2

In [ ]:
df2=df2.fillna(method='ffill')
df2.head()

/tmp/ipython-input-1485701232.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2=df2.fillna(method='ffill')

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
id,,,,,,,,,,,,,,,,,,,,,
20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,1985-02-05,34,187.96,83.0,"ST,LW",Portugal,94,94,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
138956,G. Chiellini,Giorgio Chiellini,1984-08-14,34,187.96,84.8,CB,Italy,90,90,...,74+3,76+3,76+3,76+3,74+3,77+3,86+3,86+3,86+3,77+3
139720,V. Kompany,Vincent Kompany,1986-04-10,32,190.50,84.8,CB,Belgium,85,85,...,73+3,77+3,77+3,77+3,73+3,75+3,82+3,82+3,82+3,75+3
153079,S. Agüero,Sergio Leonel Agüero del Castillo,1988-06-02,30,172.72,69.9,ST,Argentina,89,89,...,58+3,56+3,56+3,56+3,58+3,53+3,47+3,47+3,47+3,53+3
155862,Sergio Ramos,Sergio Ramos García,1986-03-30,32,182.88,82.1,CB,Spain,90,90,...,81+3,84+3,84+3,84+3,81+3,83+3,87+3,87+3,87+3,83+3

In [ ]:
df2=df2.fillna(method='bfill')
df2.head()

/tmp/ipython-input-932334927.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2=df2.fillna(method='bfill')

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
id,,,,,,,,,,,,,,,,,,,,,
20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,1985-02-05,34,187.96,83.0,"ST,LW",Portugal,94,94,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
138956,G. Chiellini,Giorgio Chiellini,1984-08-14,34,187.96,84.8,CB,Italy,90,90,...,74+3,76+3,76+3,76+3,74+3,77+3,86+3,86+3,86+3,77+3
139720,V. Kompany,Vincent Kompany,1986-04-10,32,190.50,84.8,CB,Belgium,85,85,...,73+3,77+3,77+3,77+3,73+3,75+3,82+3,82+3,82+3,75+3
153079,S. Agüero,Sergio Leonel Agüero del Castillo,1988-06-02,30,172.72,69.9,ST,Argentina,89,89,...,58+3,56+3,56+3,56+3,58+3,53+3,47+3,47+3,47+3,53+3
155862,Sergio Ramos,Sergio Ramos García,1986-03-30,32,182.88,82.1,CB,Spain,90,90,...,81+3,84+3,84+3,84+3,81+3,83+3,87+3,87+3,87+3,83+3

#FIFA DATA CLEANING WITH REMOVE

In [ ]:
df2

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
id,,,,,,,,,,,,,,,,,,,,,
20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,1985-02-05,34,187.96,83.0,"ST,LW",Portugal,94,94,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
138956,G. Chiellini,Giorgio Chiellini,1984-08-14,34,187.96,84.8,CB,Italy,90,90,...,74+3,76+3,76+3,76+3,74+3,77+3,86+3,86+3,86+3,77+3
139720,V. Kompany,Vincent Kompany,1986-04-10,32,190.50,84.8,CB,Belgium,85,85,...,73+3,77+3,77+3,77+3,73+3,75+3,82+3,82+3,82+3,75+3
153079,S. Agüero,Sergio Leonel Agüero del Castillo,1988-06-02,30,172.72,69.9,ST,Argentina,89,89,...,58+3,56+3,56+3,56+3,58+3,53+3,47+3,47+3,47+3,53+3
155862,Sergio Ramos,Sergio Ramos García,1986-03-30,32,182.88,82.1,CB,Spain,90,90,...,81+3,84+3,84+3,84+3,81+3,83+3,87+3,87+3,87+3,83+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234396,A. Davies,Alphonso Davies,2000-11-02,18,154.94,72.1,"LM,RM",Canada,72,87,...,65+2,61+2,61+2,61+2,65+2,64+2,60+2,60+2,60+2,64+2
235243,M. de Ligt,Matthijs de Ligt,1999-08-12,19,187.96,88.9,CB,Netherlands,83,92,...,74+2,77+2,77+2,77+2,74+2,75+2,81+2,81+2,81+2,75+2
235320,B. Johnsen,Björn Maars Johnsen,1991-11-06,27,195.58,81.2,ST,Norway,72,73,...,51+2,50+2,50+2,50+2,51+2,50+2,50+2,50+2,50+2,50+2
235569,T. Ndombele,Tanguy NDombèlé Alvaro,1996-12-28,22,154.94,76.2,"CM,CDM",France,80,89,...,75+2,76+2,76+2,76+2,75+2,73+2,72+2,72+2,72+2,73+2
238555,J. Savarino,Jefferson Savarino,1996-11-11,22,170.18,66.2,"RW,CAM",Venezuela,72,82,...,57+2,54+2,54+2,54+2,57+2,54+2,46+2,46+2,46+2,54+2

In [ ]:
df2.head()

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
id,,,,,,,,,,,,,,,,,,,,,
20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,1985-02-05,34,187.96,83.0,"ST,LW",Portugal,94,94,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
138956,G. Chiellini,Giorgio Chiellini,1984-08-14,34,187.96,84.8,CB,Italy,90,90,...,74+3,76+3,76+3,76+3,74+3,77+3,86+3,86+3,86+3,77+3
139720,V. Kompany,Vincent Kompany,1986-04-10,32,190.50,84.8,CB,Belgium,85,85,...,73+3,77+3,77+3,77+3,73+3,75+3,82+3,82+3,82+3,75+3
153079,S. Agüero,Sergio Leonel Agüero del Castillo,1988-06-02,30,172.72,69.9,ST,Argentina,89,89,...,58+3,56+3,56+3,56+3,58+3,53+3,47+3,47+3,47+3,53+3
155862,Sergio Ramos,Sergio Ramos García,1986-03-30,32,182.88,82.1,CB,Spain,90,90,...,81+3,84+3,84+3,84+3,81+3,83+3,87+3,87+3,87+3,83+3

In [ ]:
df2.tail()

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
id,,,,,,,,,,,,,,,,,,,,,
234396,A. Davies,Alphonso Davies,2000-11-02,18,154.94,72.1,"LM,RM",Canada,72,87,...,65+2,61+2,61+2,61+2,65+2,64+2,60+2,60+2,60+2,64+2
235243,M. de Ligt,Matthijs de Ligt,1999-08-12,19,187.96,88.9,CB,Netherlands,83,92,...,74+2,77+2,77+2,77+2,74+2,75+2,81+2,81+2,81+2,75+2
235320,B. Johnsen,Björn Maars Johnsen,1991-11-06,27,195.58,81.2,ST,Norway,72,73,...,51+2,50+2,50+2,50+2,51+2,50+2,50+2,50+2,50+2,50+2
235569,T. Ndombele,Tanguy NDombèlé Alvaro,1996-12-28,22,154.94,76.2,"CM,CDM",France,80,89,...,75+2,76+2,76+2,76+2,75+2,73+2,72+2,72+2,72+2,73+2
238555,J. Savarino,Jefferson Savarino,1996-11-11,22,170.18,66.2,"RW,CAM",Venezuela,72,82,...,57+2,54+2,54+2,54+2,57+2,54+2,46+2,46+2,46+2,54+2

In [ ]:
df2=df2.drop_duplicates()
df2

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
id,,,,,,,,,,,,,,,,,,,,,
20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,1985-02-05,34,187.96,83.0,"ST,LW",Portugal,94,94,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
138956,G. Chiellini,Giorgio Chiellini,1984-08-14,34,187.96,84.8,CB,Italy,90,90,...,74+3,76+3,76+3,76+3,74+3,77+3,86+3,86+3,86+3,77+3
139720,V. Kompany,Vincent Kompany,1986-04-10,32,190.50,84.8,CB,Belgium,85,85,...,73+3,77+3,77+3,77+3,73+3,75+3,82+3,82+3,82+3,75+3
153079,S. Agüero,Sergio Leonel Agüero del Castillo,1988-06-02,30,172.72,69.9,ST,Argentina,89,89,...,58+3,56+3,56+3,56+3,58+3,53+3,47+3,47+3,47+3,53+3
155862,Sergio Ramos,Sergio Ramos García,1986-03-30,32,182.88,82.1,CB,Spain,90,90,...,81+3,84+3,84+3,84+3,81+3,83+3,87+3,87+3,87+3,83+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234396,A. Davies,Alphonso Davies,2000-11-02,18,154.94,72.1,"LM,RM",Canada,72,87,...,65+2,61+2,61+2,61+2,65+2,64+2,60+2,60+2,60+2,64+2
235243,M. de Ligt,Matthijs de Ligt,1999-08-12,19,187.96,88.9,CB,Netherlands,83,92,...,74+2,77+2,77+2,77+2,74+2,75+2,81+2,81+2,81+2,75+2
235320,B. Johnsen,Björn Maars Johnsen,1991-11-06,27,195.58,81.2,ST,Norway,72,73,...,51+2,50+2,50+2,50+2,51+2,50+2,50+2,50+2,50+2,50+2
235569,T. Ndombele,Tanguy NDombèlé Alvaro,1996-12-28,22,154.94,76.2,"CM,CDM",France,80,89,...,75+2,76+2,76+2,76+2,75+2,73+2,72+2,72+2,72+2,73+2
238555,J. Savarino,Jefferson Savarino,1996-11-11,22,170.18,66.2,"RW,CAM",Venezuela,72,82,...,57+2,54+2,54+2,54+2,57+2,54+2,46+2,46+2,46+2,54+2

In [ ]:
threshold = 0.5 * len(df)
df2 = df2.dropna(axis=1, thresh=threshold)

In [ ]:
df2 = df2.dropna(subset=["name", "overall_rating"])

In [ ]:
cols_to_remove = ["tags", "traits"]
df = df.drop(columns=cols_to_remove, errors="ignore")

In [ ]:
cols = list(df2.columns)
cols.remove("tags")    # remove "tags" column
cols.remove("traits")

In [ ]:
df2 = df2[cols]

In [ ]:
rows_to_keep = []
for i in df2.index:
    if pd.notnull(df2.loc[i, "name"]):
        rows_to_keep.append(i)

In [ ]:
f = df2.loc[rows_to_keep]

In [ ]:
df2

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
id,,,,,,,,,,,,,,,,,,,,,
20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,1985-02-05,34,187.96,83.0,"ST,LW",Portugal,94,94,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
138956,G. Chiellini,Giorgio Chiellini,1984-08-14,34,187.96,84.8,CB,Italy,90,90,...,74+3,76+3,76+3,76+3,74+3,77+3,86+3,86+3,86+3,77+3
139720,V. Kompany,Vincent Kompany,1986-04-10,32,190.50,84.8,CB,Belgium,85,85,...,73+3,77+3,77+3,77+3,73+3,75+3,82+3,82+3,82+3,75+3
153079,S. Agüero,Sergio Leonel Agüero del Castillo,1988-06-02,30,172.72,69.9,ST,Argentina,89,89,...,58+3,56+3,56+3,56+3,58+3,53+3,47+3,47+3,47+3,53+3
155862,Sergio Ramos,Sergio Ramos García,1986-03-30,32,182.88,82.1,CB,Spain,90,90,...,81+3,84+3,84+3,84+3,81+3,83+3,87+3,87+3,87+3,83+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234396,A. Davies,Alphonso Davies,2000-11-02,18,154.94,72.1,"LM,RM",Canada,72,87,...,65+2,61+2,61+2,61+2,65+2,64+2,60+2,60+2,60+2,64+2
235243,M. de Ligt,Matthijs de Ligt,1999-08-12,19,187.96,88.9,CB,Netherlands,83,92,...,74+2,77+2,77+2,77+2,74+2,75+2,81+2,81+2,81+2,75+2
235320,B. Johnsen,Björn Maars Johnsen,1991-11-06,27,195.58,81.2,ST,Norway,72,73,...,51+2,50+2,50+2,50+2,51+2,50+2,50+2,50+2,50+2,50+2
235569,T. Ndombele,Tanguy NDombèlé Alvaro,1996-12-28,22,154.94,76.2,"CM,CDM",France,80,89,...,75+2,76+2,76+2,76+2,75+2,73+2,72+2,72+2,72+2,73+2
238555,J. Savarino,Jefferson Savarino,1996-11-11,22,170.18,66.2,"RW,CAM",Venezuela,72,82,...,57+2,54+2,54+2,54+2,57+2,54+2,46+2,46+2,46+2,54+2

In [ ]:
df2.to_csv("fifa_cleaned_removed.csv", index=False)
print(df2.shape)

(156, 89)

In [ ]:
#print all the names of the players whose age is less tha 30 and play in the centre forward position in the club
df2[(df2['age'] < 30) & (df2['positions'] == 'ST')]['name']

id
176237    J. Altidore
186562    J. Magennis
192387    C. Immobile
192505      R. Lukaku
201399      M. Icardi
202126        H. Kane
205175       A. Milik
207877    J. Martínez
210259      A. Hassan
212188      T. Werner
235320     B. Johnsen
Name: name, dtype: object